event/urls.py
from django.urls import path
from .views import EventListView, EventDetailView, EventCreateView, EventUpdateView, EventDeleteView

urlpatterns = [
    path('', EventListView.as_view(), name='event_list'),
    path('<int:pk>/', EventDetailView.as_view(), name='event_detail'),
    path('create/', EventCreateView.as_view(), name='event_create'),
    path('<int:pk>/update/', EventUpdateView.as_view(), name='event_update'),
    path('<int:pk>/delete/', EventDeleteView.as_view(), name='event_delete'),
]

school_app/urls.py
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.shortcuts import redirect
from django.urls import reverse

def admin_redirect(request):
    return redirect(reverse('admin:index'))

urlpatterns = [
    path('admin/', admin.site.urls),
    path("accounts/", include("django.contrib.auth.urls")),
    path("", include("apps.corecode.urls")),
    path("student/", include("apps.students.urls")),
    path("staff/", include("apps.staffs.urls")),
    path("finance/", include("apps.finance.urls")),
    path("expenditures/", include("expenditures.urls")),
    path("event/", include("event.urls")),
    path("result/", include("apps.result.urls")),
    path("updations/", include("updations.urls")),
    path("school_properties/", include("school_properties.urls")),
    # Add a URL pattern for redirecting to the admin site
    path('goto-admin/', admin_redirect, name='goto-admin'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

expenditures/models.py
from django.db import models

class Category(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name

class Expenditure(models.Model):
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    item_name = models.CharField(max_length=100)  # Field to store the name of the item
    amount = models.DecimalField(max_digits=10, decimal_places=2)
    date = models.DateField()
    description = models.TextField(null=True, blank=True)
    quantity = models.CharField(max_length=100, null=True, blank=True)
    attachment = models.FileField(upload_to='attachments/', null=True, blank=True)

class ExpenditureInvoice(models.Model):
    initial_balance = models.DecimalField(max_digits=10, decimal_places=2, default=0)
    date = models.DateField()
    depositor_name = models.CharField(max_length=150)

school_properties/models.py
# Create your models here.
from django.db import models
from apps.corecode.models import AcademicSession

class Property(models.Model):
    name = models.CharField(max_length=100)
    quantity = models.PositiveIntegerField(default=0)
    description = models.TextField(blank=True)
    session = models.ForeignKey(AcademicSession, on_delete=models.CASCADE)

    def __str__(self):
        return self.name

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta http-equiv="x-ua-compatible" content="ie=edge">

  <title>{{ school_name | default:"Element lakezone pre & primary school" }}</title>

  <!-- Bootstrap CSS -->
  <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
  <link href="https://stackpath.bootstrapcdn.com/bootstrap/5.1.3/css/bootstrap.min.css" rel="stylesheet">


  <!-- Font Awesome Icons -->
  <link rel="stylesheet" href="{% static 'plugins/fontawesome-free/css/all.min.css' %}">
  <link rel="stylesheet" href="{% static 'plugins/toastr/toastr.min.css' %}">
  <!-- overlayScrollbars -->
  <link rel="stylesheet" href="{% static 'plugins/overlayScrollbars/css/OverlayScrollbars.min.css' %}">
  <link rel="stylesheet" href="{% static 'plugins/Datatables/datatables.min.css' %}" />
  <!-- Theme style -->
  <link rel="stylesheet" href="{% static 'dist/css/adminlte.min.css' %}">
  <!-- Google Font: Source Sans Pro -->
  <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700" rel="stylesheet">
</head>

<body class="hold-transition sidebar-mini layout-fixed layout-navbar-fixed layout-footer-fixed">
  <div class="wrapper">
    <!-- Navbar -->
    <nav class="main-header navbar navbar-expand navbar-white navbar-light">
      <!-- Left navbar links -->
      <ul class="navbar-nav">
        <li class="nav-item">
          <a class="nav-link" data-widget="pushmenu" href="#" role="button"><i class="fas fa-bars"></i></a>
        </li>
        <li class="nav-item d-none d-sm-inline-block">
          <a href="{% url 'home' %}" class="nav-link">Home</a>
        </li>
        <li class="nav-item d-none d-sm-inline-block">
          <a class="nav-link">Year: {{ current_year}}</a>
        </li>
        <li class="nav-item d-none d-sm-inline-block">
          <a class="nav-link">Term: {{ current_term }}</a>
        </li>
      </ul>
      <ul class="navbar-nav ml-auto">
  <!-- Admin Site Link -->
  <li class="nav-item">
    <a class="nav-link" href="{% url 'goto-admin' %}">
      <i class="fas fa-cogs"></i> Admin
    </a>
  </li>
        <!-- Notifications Dropdown Menu -->
        <li class="nav-item dropdown">
          <a class="nav-link" data-toggle="dropdown" href="#">
            <i class="far fa-user"></i>
          </a>
          <div class="dropdown-menu dropdown-menu-lg dropdown-menu-right">
            <a href="#" class="dropdown-item">
              <i class="fas fa-user mr-2"></i> Profile
            </a>
            <div class="dropdown-divider"></div>
            <a href="{% url 'logout' %}" class="dropdown-item">
              <i class="fas fa-sign-out"></i> Sign out
            </a>
          </div>
        </li>
        <li class="nav-item">
          <a class="nav-link" data-widget="control-sidebar" data-slide="true" href="#" role="button"><i class="fas fa-th-large"></i></a>
        </li>
      </ul>
    </nav>
    <!-- /.navbar -->

    <!-- Main Sidebar Container -->
    <aside class="main-sidebar sidebar-dark-primary elevation-4">
      <!-- Brand Logo -->
      <a href="{% url 'home' %}" class="brand-link">{{"Elements Lakezon pre & primary school" }}</a>

      <!-- Sidebar -->
      <div class="sidebar">
        <!-- Sidebar Menu -->
        <nav class="mt-2">
          <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
            <!-- Placeholder for your app links -->
            <li class="nav-item">
               <a href="{% url 'student-list' %}" class="nav-link">
                <i class="nav-icon fas fa-graduation-cap"></i>
                <p>Pupils</p>
                </p>
              </a>
            </li>
            <li class="nav-item">
              <a href="{% url 'staff-list' %}" class="nav-link">
                <i class="nav-icon fas fa-users"></i>
                <p>
                  Staffs
                </p>
              </a>
            </li>  
            <li class="nav-header">Events</li>
            <li class="nav-item">
               <a href="{% url 'event_create' %}" class="nav-link">
                <i class="nav-icon fas fa-money-bill-alt"></i>
                <p>Add Event</p>
              </a>
            </li>
            <li class="nav-item">
                <a href="{% url 'event_list' %}" class="nav-link">
                <i class="nav-icon fas fa-money-bill-alt"></i>
                <p>View Events</p>
              </a>
            </li>
            <li class="nav-header">Finance</li>
            <li class="nav-item">
               <a href="{% url 'invoice-list' %}" class="nav-link">
                <i class="nav-icon fas fa-money-bill-alt"></i>
                <p>Payment Invoices</p>
              </a>
            </li>
            <li class="nav-item">
                <a href="{% url 'salary-invoice-list' %}" class="nav-link">
                <i class="nav-icon fas fa-money-bill-alt"></i>
                <p>Salary Invoices</p>
              </a>
            </li>
            <li class="nav-item">
               <a href="{% url 'category_list' %}" class="nav-link">
                <i class="nav-icon fas fa-list-alt"></i>
                <p>Category List</p>
              </a>
            </li>
            <li class="nav-item">
              <a href="{% url 'expenditure_list' %}" class="nav-link">
                <i class="nav-icon fas fa-money-bill"></i>
                <p>Expenditure List</p>
              </a>
            </li>
            <li class="nav-item">
            <a href="{% url 'expenditure-invoice-list' %}" class="nav-link">
                <i class="nav-icon fas fa-money-bill-alt"></i>
                <p>Expenditure Invoices</p>
              </a>
            </li>
            <li class="nav-header">Results</li>
            <li class="nav-item">
              <a href="{% url 'create-result' %}" class="nav-link">
                <i class="nav-icon fas fa-money-bill-alt"></i>
                <p>
                  Create Results
                </p>
              </a>
            </li>
            <li class="nav-item">
              <a href="{% url 'edit-results' %}" class="nav-link">
                <i class="nav-icon fas fa-money-bill-alt"></i>
                <p>
                  Update Results
                </p>
              </a>
            </li>
            <li class="nav-item">
              <a href="{% url 'single-class' %}" class="nav-link">
                <i class="nav-icon fas fa-money-bill-alt"></i>
                <p>
                  View Half Term Results
                </p>
              </a>
            </li>            
            <li class="nav-item">
              <a href="{% url 'class-list' %}" class="nav-link">
                  <i class="nav-icon fas fa-money-bill-alt"></i>
                  <p>
                      View Full Term Results
                  </p>
              </a>
          </li>
          <li class="nav-header">School Properties</li>
          <li class="nav-item has-treeview">
            <a href="#" class="nav-link">
              <i class="nav-icon fas fa-copy"></i>
              <p>
                All Properties
                <i class="fas fa-angle-left right"></i>
              </p>
            </a>
            <ul class="nav nav-treeview">
              <li class="nav-item">
                <a href="{% url 'add_property' %}" class="nav-link">
                  <i class="nav-icon fas fa-bars"></i>
                  <p>Add Property</p>
                </a>
              </li>
              <li class="nav-item">
                <a href="{% url 'property_list' %}" class="nav-link">
                  <i class="nav-icon fas fa-bars"></i>
                  <p>Manage Property</p>
                </a>
              </li>
            </ul>
          </li>        
            <li class="nav-header">Others</li>
            <li class="nav-item has-treeview">
              <a href="#" class="nav-link">
                <i class="nav-icon fas fa-copy"></i>
                <p>
                  Management
                  <i class="fas fa-angle-left right"></i>
                </p>
              </a>
              <ul class="nav nav-treeview">
                <li class="nav-item">
                  <a href="{% url 'sessions' %}" class="nav-link">
                    <i class="nav-icon fas fa-bars"></i>
                    <p>Years</p>
                  </a>
                </li>
                <li class="nav-item">
                 <a href="{% url 'terms' %}" class="nav-link">
                    <i class="nav-icon fas fa-bars"></i>
                    <p>Terms</p>
                  </a>
                </li>
                <li class="nav-item">
                  <a href="{% url 'exams' %}" class="nav-link">
                   <i class="nav-icon fas fa-bars"></i>
                    <p>Exam Type</p>
                 </a>
                </li>
                <li class="nav-item">
                 <a href="{% url 'subjects' %}" class="nav-link">
                    <i class="nav-icon fas fa-bars"></i>
                    <p>Subjects</p>
                  </a>
                </li>
                <li class="nav-item">
                   <a href="{% url 'classes' %}" class="nav-link">
                    <i class="nav-icon fas fa-bars"></i>
                    <p>Classes</p>
                  </a>
                </li>
               <li class="nav-item">
                <a href="{% url 'move_students' %}" class="nav-link">
                  <i class="nav-icon fas fa-bars"></i>
                  <p>Move Students</p>
                </a>
              </li>
              <li class="nav-item">
                <a href="{% url 'delete_students' %}" class="nav-link">
                  <i class="nav-icon fas fa-bars"></i>
                  <p>Delete Students</p>
                </a>
              </li>
              </ul>
            </li>
        </nav>
        <!-- /.sidebar-menu -->
      </div>
      <!-- /.sidebar -->
    </aside>

    <!-- Content Wrapper. Contains page content -->
    <div class="content-wrapper">
      <section class="content-header">
        <div class="container-fluid">
          <div class="row mb-1">
            <div class="col-sm-8">
              <h1>{% block title %}{% endblock title %}</h1>
            </div>
            <div class="col-sm-4">
              <ol class="breadcrumb float-sm-right">
                <li class="breadcrumb-item">{% block breadcrumb %}{% endblock breadcrumb %}</li>
              </ol>
            </div>
          </div>
        </div><!-- /.container-fluid -->
      </section>
      <!-- Main content -->
      <section class="content">
        <div class="container-fluid">
          <div class="row">
            <div class="col-md-12">
              {% block fullcard %}
              <div class="card">
                {% block content-header %}{% endblock content-header %}
                <div class="card-body">
                  <div class="row">
                    <div class="col">
                      {% block content %}

                      {% endblock content %}
                    </div>
                  </div>
                  <!-- /.row -->
                </div>
                <!-- ./card-body -->
              </div>
              {% endblock fullcard %}
              <!-- /.card -->
            </div>
            <!-- /.col -->
          </div>
          <!-- /.row -->
        </div>
        <!--/. container-fluid -->
      </section>
      <!-- /.content -->
    </div>
    <!-- /.content-wrapper -->

    <!-- Control Sidebar -->
    <aside class="control-sidebar control-sidebar-dark">
      <!-- Control sidebar content goes here -->
    </aside>
    <!-- /.control-sidebar -->
  </div>
  <!-- ./wrapper -->

  <!-- REQUIRED SCRIPTS -->
  <!-- jQuery -->
  <script src="{% static 'plugins/jquery/jquery.min.js' %}"></script>
  <!-- Bootstrap -->
  <script src="{% static 'plugins/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
  <!-- overlayScrollbars -->
  <script src="{% static 'plugins/overlayScrollbars/js/jquery.overlayScrollbars.min.js' %}"></script>
  <!-- AdminLTE App -->
  <script src="{% static 'dist/js/adminlte.js' %}"></script>
  <!-- OPTIONAL SCRIPTS -->
  <script src="{% static 'dist/js/demo.js' %}"></script>
  <!-- Toastr -->
  <script src="{% static 'plugins/toastr/toastr.min.js' %}"></script>
  <!-- Datatables -->
  <script src="{% static 'plugins/Datatables/datatables.min.js' %}"></script>

  {% if messages %}
  {% for message in messages %}
  <script type=text/javascript>
    toastr.options.progressBar = true;
    toastr.{{ message.tags }}('{{ message }}')
  </script>
  {% endfor %}
  {% endif %}

  <script>
    (function ($) {
      $('.clickable-row').css('cursor', 'pointer');
      $(".clickable-row").click(function () {
        window.location = $(this).data("href");
      });
    })(jQuery)
  </script>

  {% block morejs %}

  {% endblock morejs %}
</body>
</html>

templates/index.html
{% extends 'base.html' %}


{% block content %}
  <p>Dashboard contents and design coming soon.</p>
  <p> Use the sidebar menu for now!</p>
{% endblock content %}

templates/paginator.html
{% if page_obj.has_other_pages %}
<div aria-label="pagination">
  <ul class="pagination justify-content-center">
    {% if page_obj.has_previous %}
      <li class="page-item">
        <a class="page-link" href="?page={{ page_obj.previous_page_number }}" tabindex="-1">Previous</a>
      </li>
    {% endif %}

    {% for page in page_obj.paginator.page_range %}

      {% if page_obj.number == page %}
        <li class="page-item active" aria-current="page">
          <span class="page-link">{{ page }}<span class="sr-only">(current)</span>
          </span>
        </li>
      {% else %}
        <li class="page-item"><a class="page-link" href="?page={{ page }}">{{ page }}</a></li>
      {% endif %}

    {% endfor %}

    {% if page_obj.has_next %}
      <li class="page-item">
        <a class="page-link" href="?page={{ page_obj.next_page_number }}">Next</a>
      </li>
      {% endif %}
  </ul>
</div>

{% endif %}